import "dotenv/config";

const baseUrl = process.env.BASE_URL || "http://127.0.0.1:3002";

async function fetchText(path: string) {
  const response = await fetch(`${baseUrl}${path}`);
  const text = await response.text();
  if (response.status !== 200) throw new Error(`${path} failed HTTP ${response.status}: ${text.slice(0, 300)}`);
  return text;
}

function assertIncludes(body: string, text: string, label: string) {
  if (!body.includes(text)) throw new Error(`${label}: missing "${text}".`);
}

function assertNotIncludes(body: string, text: string, label: string) {
  if (body.includes(text)) throw new Error(`${label}: still includes "${text}".`);
}

async function main() {
  const home = await fetchText("/");
  assertIncludes(home, "<html lang=\"vi\"", "Root html");
  assertIncludes(home, "ShopOnline", "Home metadata");
  assertNotIncludes(home, "Create Next App", "Home metadata");
  assertNotIncludes(home, "Generated by create next app", "Home metadata");

  const login = await fetchText("/admin/login");
  assertIncludes(login, "Đăng nhập quản trị", "Admin login");
  assertIncludes(login, "Về website", "Admin login");
  for (const broken of ["??ng", "qu?n", "D?ng", "V? website", "m?t kh?u", "T?i kho?n"]) {
    assertNotIncludes(login, broken, "Admin login mojibake check");
  }

  console.log("ShopOnline readiness smoke passed");
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
