"use client";

import { useMemo, useState, useTransition } from "react";
import { archiveUserAction, createUserAction, resetUserPasswordAction, updateUserAction } from "./actions";

type UserRow = { id: string; name: string; email: string; role: string; status: string; createdAt: string; updatedAt: string };
type ModalState = { mode: "create" } | { mode: "edit"; row: UserRow } | { mode: "password"; row: UserRow } | null;
const roles = ["ADMIN", "MANAGER", "SALES", "WAREHOUSE", "ACCOUNTANT", "MARKETING"];
const statuses = ["ACTIVE", "DRAFT", "HIDDEN", "ARCHIVED"];

export function UsersClient({ rows, currentUserId }: { rows: UserRow[]; currentUserId: string }) {
  const [query, setQuery] = useState("");
  const [role, setRole] = useState("");
  const [status, setStatus] = useState("");
  const [modal, setModal] = useState<ModalState>(null);
  const filtered = useMemo(() => {
    const term = query.trim().toLowerCase();
    return rows.filter((row) => (!term || [row.name, row.email].some((value) => value.toLowerCase().includes(term))) && (!role || row.role === role) && (!status || row.status === status));
  }, [query, role, rows, status]);
  return (
    <main className="min-h-screen bg-slate-50 p-6 text-slate-950">
      <div className="mx-auto grid max-w-7xl gap-6">
        <header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-emerald-700">Admin / Người dùng</p><h1 className="text-3xl font-semibold">Quản lý người dùng</h1><p className="mt-1 text-sm text-slate-600">Tạo tài khoản, phân vai trò, khóa tài khoản và reset mật khẩu.</p></div><button className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white" onClick={() => setModal({ mode: "create" })}>Tạo người dùng</button></header>
        <section className="grid gap-4 md:grid-cols-4"><Metric label="Tổng user" value={rows.length} /><Metric label="Đang hoạt động" value={rows.filter((row) => row.status === "ACTIVE").length} /><Metric label="Quản trị" value={rows.filter((row) => row.role === "ADMIN").length} /><Metric label="Đã lưu trữ" value={rows.filter((row) => row.status === "ARCHIVED").length} /></section>
        <section className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_180px_180px_auto]"><label className="grid gap-1 text-sm font-semibold text-slate-700">Tìm kiếm<input className="rounded-lg border border-slate-300 px-3 py-2 font-normal" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tên hoặc email" /></label><label className="grid gap-1 text-sm font-semibold text-slate-700">Vai trò<select className="rounded-lg border border-slate-300 px-3 py-2 font-normal" value={role} onChange={(event) => setRole(event.target.value)}><option value="">Tất cả</option>{roles.map((item) => <option key={item} value={item}>{viRole(item)}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold text-slate-700">Trạng thái<select className="rounded-lg border border-slate-300 px-3 py-2 font-normal" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tất cả</option>{statuses.map((item) => <option key={item} value={item}>{viStatus(item)}</option>)}</select></label><div className="flex items-end text-sm font-semibold text-slate-600">{filtered.length} dòng</div></section>
        <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr><th className="px-4 py-3">Người dùng</th><th className="px-4 py-3">Vai trò</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Ngày tạo</th><th className="px-4 py-3 text-right">Thao tác</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="px-4 py-3"><strong>{row.name}</strong><p className="mt-1 text-xs text-slate-500">{row.email}</p></td><td className="px-4 py-3">{viRole(row.role)}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{viStatus(row.status)}</span></td><td className="px-4 py-3">{dateText(row.createdAt)}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><button className="rounded-lg border border-slate-300 px-3 py-2 font-semibold" onClick={() => setModal({ mode: "edit", row })}>Sửa</button><button className="rounded-lg border border-slate-300 px-3 py-2 font-semibold" onClick={() => setModal({ mode: "password", row })}>Reset mật khẩu</button>{row.status !== "ARCHIVED" && row.id !== currentUserId ? <ArchiveButton row={row} /> : null}</div></td></tr>)}{!filtered.length ? <tr><td className="px-4 py-10 text-center text-slate-500" colSpan={5}>Không có người dùng phù hợp.</td></tr> : null}</tbody></table></div></section>
      </div>
      {modal?.mode === "create" || modal?.mode === "edit" ? <UserModal modal={modal} onClose={() => setModal(null)} /> : null}
      {modal?.mode === "password" ? <PasswordModal row={modal.row} onClose={() => setModal(null)} /> : null}
    </main>
  );
}

function UserModal({ modal, onClose }: { modal: Extract<ModalState, { mode: "create" } | { mode: "edit"; row: UserRow }>; onClose: () => void }) { const row = modal.mode === "edit" ? modal.row : null; const action = row ? updateUserAction : createUserAction; const [pending, startTransition] = useTransition(); return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); const formData = new FormData(event.currentTarget); startTransition(async () => { await action(formData); window.location.reload(); }); }} className="grid w-full max-w-2xl gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-xl"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><h2 className="text-xl font-semibold">{row ? "Sửa người dùng" : "Tạo người dùng"}</h2><button type="button" className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold" onClick={onClose}>Đóng</button></div>{row ? <input type="hidden" name="id" value={row.id} /> : null}<div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm font-semibold text-slate-700">Tên<input required className="rounded-lg border border-slate-300 px-3 py-2 font-normal" name="name" defaultValue={row?.name || ""} /></label><label className="grid gap-1 text-sm font-semibold text-slate-700">Email<input required className="rounded-lg border border-slate-300 px-3 py-2 font-normal" name="email" type="email" defaultValue={row?.email || ""} /></label>{!row ? <label className="grid gap-1 text-sm font-semibold text-slate-700">Mật khẩu<input required className="rounded-lg border border-slate-300 px-3 py-2 font-normal" name="password" type="password" minLength={6} defaultValue="ShopOnline@2026" /></label> : null}<label className="grid gap-1 text-sm font-semibold text-slate-700">Vai trò<select className="rounded-lg border border-slate-300 px-3 py-2 font-normal" name="role" defaultValue={row?.role || "SALES"}>{roles.map((item) => <option key={item} value={item}>{viRole(item)}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold text-slate-700">Trạng thái<select className="rounded-lg border border-slate-300 px-3 py-2 font-normal" name="status" defaultValue={row?.status || "ACTIVE"}>{statuses.map((item) => <option key={item} value={item}>{viStatus(item)}</option>)}</select></label></div><div className="flex justify-end gap-2 border-t border-slate-100 pt-3"><button type="button" className="rounded-lg border border-slate-300 px-4 py-2 font-semibold" onClick={onClose}>Huỷ</button><button type="submit" className="rounded-lg bg-slate-950 px-4 py-2 font-semibold text-white disabled:opacity-60" disabled={pending}>{pending ? "Đang lưu..." : "Lưu"}</button></div></form></div>; }
function PasswordModal({ row, onClose }: { row: UserRow; onClose: () => void }) { const [pending, startTransition] = useTransition(); return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); const formData = new FormData(event.currentTarget); startTransition(async () => { await resetUserPasswordAction(formData); window.location.reload(); }); }} className="grid w-full max-w-md gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-xl"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><h2 className="text-xl font-semibold">Reset mật khẩu</h2><button type="button" className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold" onClick={onClose}>Đóng</button></div><input type="hidden" name="id" value={row.id} /><p className="text-sm text-slate-600">{row.name} - {row.email}</p><label className="grid gap-1 text-sm font-semibold text-slate-700">Mật khẩu mới<input required className="rounded-lg border border-slate-300 px-3 py-2 font-normal" name="password" type="password" minLength={6} defaultValue="ShopOnline@2026" /></label><div className="flex justify-end gap-2 border-t border-slate-100 pt-3"><button type="button" className="rounded-lg border border-slate-300 px-4 py-2 font-semibold" onClick={onClose}>Huỷ</button><button type="submit" className="rounded-lg bg-slate-950 px-4 py-2 font-semibold text-white disabled:opacity-60" disabled={pending}>{pending ? "Đang lưu..." : "Reset"}</button></div></form></div>; }
function ArchiveButton({ row }: { row: UserRow }) { const [pending, startTransition] = useTransition(); return <button className="rounded-lg border border-red-200 px-3 py-2 font-semibold text-red-700 disabled:opacity-60" disabled={pending} onClick={() => { if (!confirm("Lưu trữ người dùng này?")) return; const formData = new FormData(); formData.set("id", row.id); startTransition(async () => { await archiveUserAction(formData); window.location.reload(); }); }}>{pending ? "Đang lưu..." : "Lưu trữ"}</button>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span className="text-sm text-slate-500">{label}</span><strong className="mt-2 block text-2xl">{value}</strong></article>; }
function dateText(value: string) { return new Intl.DateTimeFormat("vi-VN", { dateStyle: "short" }).format(new Date(value)); }
function viRole(role: string) { return ({ ADMIN: "Quản trị", MANAGER: "Quản lý", SALES: "Bán hàng", WAREHOUSE: "Kho", ACCOUNTANT: "Kế toán", MARKETING: "Marketing" } as Record<string, string>)[role] || role; }
function viStatus(status: string) { return ({ ACTIVE: "Đang hoạt động", DRAFT: "Nháp", HIDDEN: "Khoá", ARCHIVED: "Lưu trữ" } as Record<string, string>)[status] || status; }
